### ISSUE TITLE
practica 8 

### ISSUE THREAD

**Issue by Yareli-Perez** [SistemasTecTlaxiaco/practica-de-visualizacion-de-datos-topicos4yan#1]
[Practica 8.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-visualizacion-de-datos-topicos4yan/files/8750263/Practica.8.pdf)

**Comment by Gregorio012** [comment]
Calificación 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
